### ISSUE TITLE
Alternative commands also appear on the site (on the command-list page)

### ISSUE THREAD

**Issue by igdiaysu** [senchabot-dev/monorepo#100]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

![resim](https://user-images.githubusercontent.com/87132161/236030859-da6b790f-8ee1-4c5f-90df-ff77a3a37e71.png)

**Comment by sevilayerkan** [comment]
Congrats for #100 th issue 🥳

**Comment by cookiedaddy6** [comment]
im intrested in this one

**Comment by cookiedaddy6** [comment]
it lookes realy fun to do
