### ISSUE TITLE
bug/feat(twitch): Alias editing

### ISSUE THREAD

**Issue by sevilayerkan** [senchabot-dev/monorepo#105]
**Describe the bug**
When we edit the alias (ucmd) it should change the text of the main command. It can detect the main command and add alias to it. 

This issue also connected with issue #104 

Here is an example usage for that: 
![image](https://user-images.githubusercontent.com/22706692/236203700-c2240b06-7c35-45f9-8097-2dace0b87903.png)

**Comment by durmusrasit** [comment]
This can also be done for the `dcmd` command.
