### ISSUE TITLE
BUG. on settings tab/page

### ISSUE THREAD

**Issue by GraphicEdit** [senchabot-dev/monorepo#126]
**Describe the bug**
App dosent show full email on users settings tab/page

**To Reproduce**
1. Go to 'app/settings (security)'
2. You will see there "Your e-mail address" but it's not full length e-mail address

**Expected behavior**
it should be show full length e-mail address

**Screenshots**
![Xr9wvVVvam](https://github.com/senchabot-dev/monorepo/assets/1042534/a2a0f100-1089-4c3a-8442-f7032f13d3f1)

**Desktop (please complete the following information):**
 - OS: win 64
 - Browser Firefox 
 - Version 113.0

**Comment by mertsabinov** [comment]
Hello @GraphicEdit 

Thank you very much for your feedback. We appreciate it, and we are aware of this situation. We deliberately do this to ensure the security of our users, as their safety is of utmost importance to us. Therefore, we only show a certain part of their email addresses to prevent users from inadvertently revealing their personal email addresses during broadcasts.

**Comment by mertsabinov** [comment]
Hello @GraphicEdit 

Thank you very much for your feedback. We appreciate it, and we are aware of this situation. We deliberately do this to ensure the security of our users, as their safety is of utmost importance to us. Therefore, we only show a certain part of their email addresses to prevent users from inadvertently revealing their personal email addresses during broadcasts.

**Comment by batuhanbaybas** [comment]
we can show b***@email.com format we can discuss this situation
