### ISSUE TITLE
Save button remains active after switching from 'disable' to 'enable' without clicking it

### ISSUE THREAD

**Issue by mertsabinov** [senchabot-dev/monorepo#148]
**Describe the bug:**

When the "enable" option is selected in the settings page, the save button remains disabled as expected. However, after switching to the "disable" option, the save button becomes active. When switching back to the "enable" option without clicking the save button, the save button should return to its disabled state, but it remains active.

**To Reproduce:**
1. Go to the settings page.
2. Select the "enable" option.
3. Verify that the save button is disabled.
4. Select the "disable" option.
5. Verify that the save button becomes active.
6. Select the "enable" option again without clicking the save button.
7. Observe that the save button remains active instead of returning to its disabled state.

**Expected behavior:**

The save button should return to its disabled state when the "enable" option is selected again without clicking the save button.

not: all this should also be when disable is selected

https://github.com/senchabot-dev/monorepo/assets/88425310/993ff109-0e50-43f9-b7b1-dd9433c45e02

**Comment by batuhanbaybas** [comment]
when i check the issue there is no problem for that usage because user not confirm their action when select bot config on first time

**Comment by mertsabinov** [comment]
Hello @batuhanbaybas ,

Thank you for your valuable comment. I have considered the issue and understand the points you have raised. It is true that users should confirm their changes by clicking the save button before they take effect.

However, I believe that the reported bug is indeed a valid issue. It seems that the save button not updating its state after users change their options does not align with the expected behavior. When users revert to their previous selection, the save button should be disabled as per the expected behavior.

While considering usability, it can be argued that users need to click the save button to confirm their changes. However, in this case, the save button's state should be updated based on the user's selections and reflect the expected behavior.

Therefore, in order to address the bug, we need to track the state of the save button and update it correctly when users modify their options. The save button should be disabled when users return to their previous selection.
