### ISSUE TITLE
feat(apps/twitch-bot): Add new global command to direct questions to Kampus

### ISSUE THREAD

**Issue by sevilayerkan** [senchabot-dev/monorepo#165]
**Is your feature request related to a problem? Please describe.**
As we see there is need to add global command to direct questions to the `Kampus`. 

**Describe the solution you'd like**
For resolve this we can a global command like:

**Command:** `!kampusesor`
**Response:** `Sorularınızı !kampus deki kampus-soru-cevap kanalına sorabilirsiniz.`

**Describe alternatives you've considered**

**Additional context**

**Comment by durmusrasit** [comment]
Thanks for the issue. This cannot be done due to moderation issues. So I'm closing the issue.
