### ISSUE TITLE
if user click show email button we should show full email address

### ISSUE THREAD

**Issue by mertsabinov** [senchabot-dev/monorepo#27]
**Is your feature request related to a problem? Please describe.**
if user click show email button we should show full email address

**Describe the solution you'd like**
we should show full user email address

If found suitable I would like to be Assignees

**Comment by durmusrasit** [comment]
I think it is necessary because it prevents the disclosure of e-mail information if this security section is open in a public environment

**Comment by mertsabinov** [comment]
> I think it is necessary because it prevents the disclosure of e-mail information if this security section is open in a public environment

I understand your concern and I think it makes sense, so I'm retracting my request for this development.
