### ISSUE TITLE
Landingpage Footer's pre-alpha v0.1 text not updating in other footers

### ISSUE THREAD

**Issue by mertsabinov** [senchabot-dev/monorepo#47]
The pre-alpha v0.1 text in the Landingpage footer is not visible and not updating in other footers of the application. It should be consistent with other footers.

### expected behavior
![Screenshot 2023-04-17 at 16 16 23](https://user-images.githubusercontent.com/88425310/232495280-45959df0-c1c7-4dd8-9e92-39a81c961d58.png)

current behavior (application footer)
![Screenshot 2023-04-17 at 16 17 37](https://user-images.githubusercontent.com/88425310/232495529-fcfb2195-4dc3-4e03-abd0-2609002022ea.png)

**Comment by Subham5401** [comment]
Hi, I would like to go ahead with this.

**Comment by mertsabinov** [comment]
> Hi, I would like to go ahead with this.

Hello, @Subham5401  
I don't see any problem with you continuing with this. Good luck with your work!

**Comment by Subham5401** [comment]
@mertsabinov  Could you tell which app amongst discord-bot, reflect and twitch-bot has the issue?

**Comment by mertsabinov** [comment]
> @mertsabinov Could you tell which app amongst discord-bot, reflect and twitch-bot has the issue?

Of course `reflect`
