### ISSUE TITLE
Add a Checkbox to Confirm Acceptance of Terms and Conditions on User Login Page

### ISSUE THREAD

**Issue by mertsabinov** [senchabot-dev/monorepo#48]
Hello,

My suggestion is to add a checkbox for users to confirm acceptance of the terms and conditions before logging in. This is important to protect the security and privacy of user data by preventing users from logging in without reading the terms and conditions.

Thank you.

![Screenshot 2023-04-17 at 16 25 40](https://user-images.githubusercontent.com/88425310/232497586-60c77696-4f05-4c58-b892-14c23f3aa182.png)

**Comment by cookiedaddy6** [comment]
this one

**Comment by cancng** [comment]
#158
